### ISSUE TITLE
Invalid method 'isWXAppInstalled'

### ISSUE THREAD

**Issue by Obooman** [beefe/react-native-wechat-ios#11]
Awesome project and it really help me a lot.However,I run my app on my ipod,the isWXAppInstalled method return 'false' - however,I have wechat in my iPod.

Any suggestion?

react-native version 0.17.0.

**Comment by xiaoyann** [comment]
- http://www.jianshu.com/p/e38a609f786e
- https://github.com/beefe/react-native-wechat-ios/commit/771da5dbb1b9c5da86846d8aade53020a75ef96d

**Comment by Obooman** [comment]
Page not found.Any other suggestions?

**Comment by xiaoyann** [comment]
- http://www.jianshu.com/p/e38a609f786e
