### ISSUE TITLE
symbol(s) not found for architecture arm64

### ISSUE THREAD

**Issue by naivehhr** [beefe/react-native-wechat-ios#12]
Hello,Beefe.这是个很赞的组件!
在按照文档步骤操作[根据微信SDK文档需要做的一些设置
](https://github.com/beefe/react-native-wechat-ios#3-根据微信sdk文档需要做的一些设置)时遇到如下错误：

**========================添加库文件=========================**
<img width="701" alt="2016-04-17 10 33 59 pm" src="https://cloud.githubusercontent.com/assets/5243456/14587929/cca3f0be-04ee-11e6-9d9b-f52b918b8a95.png">
**=========================================================**
<img width="661" alt="2016-04-17 10 42 20" src="https://cloud.githubusercontent.com/assets/5243456/14587928/cca0dc8a-04ee-11e6-8e95-016df7ab10d7.png">
**==========================错误信息=========================**
<img width="551" alt="2016-04-17 10 43 15" src="https://cloud.githubusercontent.com/assets/5243456/14587927/cca0bd36-04ee-11e6-9249-bceec8d8f134.png">
Xcode：version 7.3
不太了解ios开发，劳烦指教，谢谢！

**Comment by xiaoyann** [comment]
添加 libRCTWeChat.a 没有？

**Comment by naivehhr** [comment]
@yannxiao 多谢回复！
已经添加了
<img width="641" alt="2016-04-18 10 20 25" src="https://cloud.githubusercontent.com/assets/5243456/14592252/3277dd0a-054f-11e6-9cd2-f8c242231711.png">

**Comment by naivehhr** [comment]
@yannxiao 
这里会有影响吗？
引用的是libc++.dylib 实际上是libc++.1.dylib
引用的是libsqlite3.0.dylib 实际上是libsqlite3.dylib

而且三个库全引用.tbd文件不会出现引用文件**自动更改**的问题，但是还是ld: symbol(s) not found for architecture arm64
<img width="614" alt="2016-04-18 10 52 28" src="https://cloud.githubusercontent.com/assets/5243456/14592661/b526f192-0553-11e6-9a8b-9d6128f8aecd.png">

============这是所有的引用库===========

<img width="650" alt="2016-04-18 10 53 42" src="https://cloud.githubusercontent.com/assets/5243456/14592679/ef094324-0553-11e6-8c06-2595ae323acb.png">

**Comment by xiaoyann** [comment]
这个libRCTWeChat.a 是支持 arm64 的，感觉还是你哪里的配置有问题，自己再折腾折腾吧，我对iOS也不是很懂

**Comment by naivehhr** [comment]
应该是我的问题，新建个项目在导入组件后就成功运行了。谢了！

**Comment by naivehhr** [comment]
@yannxiao 搞定，issue可以关了:）
