### ISSUE TITLE
调用支付接口失败

### ISSUE THREAD

**Issue by zhangshuai** [beefe/react-native-wechat-ios#15]
"_reactNativeWechatIos2.default.weChatPay is not a function"
@xiaoyann 调用时候是大写的:)
WeChat.weChatPay(payOptions,(res) => {
     console.log(res);
});
直接复制的示例里的代码

**Comment by xiaoyann** [comment]
你是怎么调用的？方法名写错了吧，应该是大写的 C，weChatPay。😄

**Comment by shexiaoheng** [comment]
@zhangshuai 试下wechatPay

**Comment by shexiaoheng** [comment]
@zhangshuai 你打印下WeChat，看看包含哪些方法和属性

**Comment by xiaoyann** [comment]
😄，你把你的package.json稍微改下：

```
"react-native-wechat-ios": "https://github.com/beefe/react-native-wechat-ios.git"
```

不好意思啊，这次添加支付功能忘记发布到npm了。待会发布下。

**Comment by xiaoyann** [comment]
已经发布了，现在安装 0.3.0 应该没这个问题了。

**Comment by zhangshuai** [comment]
可以调用了，谢谢:)

**Comment by tranren** [comment]
调用支付方法，可以跳转到微信，但支付不了
