### ISSUE TITLE
macOs sierra  10.12.1编译错误

### ISSUE THREAD

**Issue by MedusaLeee** [beefe/react-native-wechat-ios#19]
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_RCTWeChat", referenced from:
      objc-class-ref in AppDelegate.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

使用提供的example也是一样的错误

**Comment by xiaoyann** [comment]
1. 这个跟你的 xcode 设置有关，https://www.google.com.ph/search?q=undefined+symbols+for+architecture+arm64&oq=undefined+symbols+for+architecture+arm64&gs_l=serp.3...7376.8470.0.8895.8.7.0.0.0.0.328.328.3-1.1.0....0...1c.1.64.serp..8.0.0.J5v-tuRBy1Q
2. 严格按照文档来了吗，该添加的添加哦
