### ISSUE TITLE
支付，分享没有回调结果，参考解决方案

### ISSUE THREAD

**Issue by macxie** [beefe/react-native-wechat-ios#21]
@shexiaoheng 
我在开发微信支付，分享都遇到没有回调结果的问题，但是使用example测试又没有问题。
在网上找了好向天之后在参考
#18 

http://blog.csdn.net/sinat_29789455/article/details/52584419
以及参考支付宝的配置后，
在AppDelegate.m文件中添加下面代码，就可以成功检测到回调
//// NOTE: alipay 9.0以后使用新API接口
- (BOOL)application:(UIApplication *)app openURL:(NSURL *)url options:(NSDictionary<NSString*, id> *)options
{
    if ([url.host isEqualToString:@"safepay"]) {
        // 支付跳转支付宝钱包进行支付，处理支付结果
       [AlipayModule handleCallback:url];
       return YES;
    } else {
      return [[RCTWeChat shareInstance] handleOpenURL: url];
    }
  
}

希望对遇到IOS 微信没有回调情况有帮助

**Comment by shexiaoheng** [comment]
@macxie 非常感谢你的分享，我负责Android端，iOS端的问题要 @xiaoyann 哦   :)
