### ISSUE TITLE
分享图片这个版本可以实现么?好像只有链接的样子

### ISSUE THREAD

**Issue by buhe** [beefe/react-native-wechat-ios#4]
分享图片这个版本可以实现么?好像只有链接的样子

**Comment by xiaoyann** [comment]
对，现在只实现了链接分享，分享图片有空看看，你也可以看看我的代码自己实现，很简单的。

**Comment by buhe** [comment]
ok 正在搞。 回头 pr

**Comment by xiaoyann** [comment]
好的，非常期待，那我就忙我的APP去啦:smile:

**Comment by buhe** [comment]
@yannxiao  已经提交 pr ,有空 review,是比较简单.

**Comment by xiaoyann** [comment]
好的，:+1:
