### ISSUE TITLE
 where is  share local photos's function in your code

### ISSUE THREAD

**Issue by qwe11345** [beefe/react-native-wechat-ios#9]
where is  share local photos's function in your code. please

**Comment by xiaoyann** [comment]
1. https://github.com/beefe/react-native-wechat-ios/blob/master/index.js#L77
2. https://github.com/beefe/react-native-wechat-ios/blob/master/RCTWeChat/RCTWeChat/RCTWeChat.m#L175

**Comment by qwe11345** [comment]
Thanks anyway. I use react-native-wechat this component
